### PR TITLE
fix(deps): update dependency shell-quote to 1.7.3

### PR DESCRIPTION
**Pull request by dustincrogers**
🎉 Thanks for submitting a pull request! 🎉

#### Summary

Fixes https://github.com/netlify/cli/security/dependabot/57

---

For us to review and ship your PR efficiently, please perform the following steps:

- [X] Open a [bug/issue](https://github.com/netlify/cli/issues/new/choose) before writing your code 🧑‍💻. This ensures we can discuss the changes and get feedback from everyone that should be involved. If you\`re fixing a typo or something that\`s on fire 🔥 (e.g. incident related), you can skip this step.
- [X] Read the [contribution guidelines](../CONTRIBUTING.md) 📖. This ensures your code follows our style guide and
      passes our tests.
- [X] Update or add tests (if any source code was changed or added) 🧪
- [X] Update or add documentation (if features were changed or added) 📝
- [x] Make sure the status checks below are successful ✅

**A picture of a cute animal (not mandatory, but encouraged)**

### CODE REVIEW

**Review by eduardoboucas — DISMISSED** [review]

**Review by danez — CHANGES_REQUESTED** [review]
Unfortunately, we cannot simply modify the `package-lock.json` file. 
We would need to update whatever is requiring `shell-quote` which would be `react-dev-tools` which in turn is required by `@compositor/x0` which is unmaintained.
So long story short, there is currently nothing we can quickly do unless we want to migrate away from `@compositor/x0`

**Comment by dustincrogers** [comment]
@danez please excuse the delay. thank you for explaining, and I did realize that during my attempt to upgrade this. `compositor/x0` is currently sparking 3 critical security alerts, and a number of high and below security alerts. 
We need to decide a next action to take here. 
- We have to understand the actual risk of running this unmaintained version of `compositor/x0`.
- Ideally each one of the security alerts (see image below) needs to be attested to. If we feel the risk is lower than critical, we can adjust. 
- I can move this discussion to an issue now if that makes more sense. 
cc: @krider2010 @markdorsi 

Screen Shot 2022-11-29 at 8 04 41 AM

**Comment by krider2010** [comment]
@dustincrogers an issue would be the best thing. We need to understand the implications of that vulnerability when run in the context of the CLI. Moving a transitive dependency across those versions is not possible, and removing a dependency like this is some engineering effort. As ever, trade offs 😸

**Review by danez — APPROVED** [review]
I updated shell-quote wherever we could and run `npm audit fix` in the site folder. Also created a new issue #5516 that I would love to work on.

**Pull request merged**
