### PR TITLE
fix: fixes an issue with npm 6

### LINKED ISSUE #3869: Cannot install `netlify-cli` with `npm@6`
**Describe the bug**

Running `npm install netlify-cli` with `npm@6` produces the following error:

```
npm WARN checkPermissions Missing write access to /home/user/repo/node_modules/netlify-cli/node_modules/eslint-plugin-local-rules

npm ERR! code ENOENT
npm ERR! syscall access
npm ERR! path /home/user/repo/node_modules/netlify-cli/node_modules/eslint-plugin-local-rules
npm ERR! errno -2
npm ERR! enoent ENOENT: no such file or directory, access '/home/uer/repo/node_modules/netlify-cli/node_modules/eslint-plugin-local-rules'
npm ERR! enoent This is related to npm not being able to find a file.
npm ERR! enoent
```

**To Reproduce**

  - Use `npm@6`.
  - Run `npm install netlify-cli`

**Configuration**

```
  System:
    OS: Linux 5.13 Ubuntu 21.10 21.10 (Impish Indri)
    CPU: (16) x64 Intel(R) Core(TM) i9-9900K CPU @ 3.60GHz
    Memory: 53.95 GB / 62.75 GB
    Container: Yes
    Shell: 5.1.8 - /bin/bash
  Binaries:
    Node: 14.18.1 - ~/.nvm/versions/node/v14.18.1/bin/node
    Yarn: 1.22.17 - ~/.nvm/versions/node/v14.18.1/bin/yarn
    npm: 6.14.15 - ~/.nvm/versions/node/v14.18.1/bin/npm
  npmPackages:
    netlify-cli: ^8.2.0 => 8.2.0
```

**Expected behavior**

Users of `npm@6` should be able to install `netlify-cli`.
`netlify-cli` supports Node 12 and 14 which come both with `npm@6`, so we need to support it.

**Additional context**

The problem seems to be this line of code, which was introduced by the Oclif removal (https://github.com/netlify/cli/pull/3717):

https://github.com/netlify/cli/blob/5ffbd6c5c74c27d0a625c6db57a434fcaa800544/package.json#L196

### PR DESCRIPTION
**Pull request by lukasholzer**
🎉 Thanks for submitting a pull request! 🎉

#### Summary

Fixes #3869

I tried running `netlify-cli@8.2.0-rc.0` and it worked. Sadly I could not reproduce it by running `npm install netlify-cli` on the latest version.

I did so on:

```

────────────────────┐
 Environment Info   │
────────────────────┘

  System:
    OS: macOS 12.1
    CPU: (10) x64 Apple M1 Max
  Binaries:
    Node: 12.22.7 - ~/.nvm/versions/node/v12.22.7/bin/node
    npm: 6.14.15 - ~/.nvm/versions/node/v12.22.7/bin/npm
  Browsers:
    Chrome: 96.0.4664.110
    Safari: 15.2

```

maybe @ehmicky you can verify if the rc version works for you?
---

For us to review and ship your PR efficiently, please perform the following steps:

- [ ] Open a [bug/issue](https://github.com/netlify/cli/issues/new/choose) before writing your code 🧑‍💻. This ensures we can discuss the changes and get feedback from everyone that should be involved. If you\`re fixing a typo or something that\`s on fire 🔥 (e.g. incident related), you can skip this step.
- [ ] Read the [contribution guidelines](../CONTRIBUTING.md) 📖. This ensures your code follows our style guide and
      passes our tests.
- [ ] Update or add tests (if any source code was changed or added) 🧪
- [ ] Update or add documentation (if features were changed or added) 📝
- [ ] Make sure the status checks below are successful ✅

**A picture of a cute animal (not mandatory, but encouraged)**

### CODE REVIEW

**Comment by lukasholzer** [comment]
> This is unfortunately still failing:
> 
> ```
> $ nvm use 12
> Now using node v12.20.0 (npm v6.14.8)
> 
> $ npm i netlify-cli@8.2.0-rc.0
> npm WARN checkPermissions Missing write access to /home/user/repo/node_modules/netlify-cli/node_modules/eslint-plugin-local-rules
> 
> npm ERR! code ENOENT
> npm ERR! syscall access
> npm ERR! path /home/user/repo/node_modules/netlify-cli/node_modules/eslint-plugin-local-rules
> npm ERR! errno -2
> npm ERR! enoent ENOENT: no such file or directory, access '/home/user/repo/node_modules/netlify-cli/node_modules/eslint-plugin-local-rules'
> npm ERR! enoent This is related to npm not being able to find a file.
> npm ERR! enoent 
> ```
> 
> It seems like using `file:` as a version in dependencies might be incompatible with `npm@6` 🤔

really weird as I cannot reproduce it on my machine with npm@6. Wich version are you using exactly?

**Comment by ehmicky** [comment]
I am using `v12.20.0 (npm v6.14.8)`. 
Maybe this is OS-specific? I am on Linux (Ubuntu).

**Comment by lukasholzer** [comment]
> I am using `v12.20.0 (npm v6.14.8)`. Maybe this is OS-specific? I am on Linux (Ubuntu).

Good Point! I'm on MacOS and used `v12.22.7 (npm 6.14.15)

**Comment by lukasholzer** [comment]
@ehmicky now I start thinking that your machine has maybe an issue: 

Just setted up a VM with ubuntu install node.js and npm 6 and it works:

CleanShot 2021-12-20 at 18 21 29@2x

**Comment by ehmicky** [comment]
I think I have found a few sites which seem to reproduce this problem. I have added the links on the [main issue](https://github.com/netlify/cli/issues/3869#issuecomment-998149240).

**Comment by erezrokah** [comment]
Looks like `npm` [recommends](https://docs.npmjs.com/resolving-eacces-permissions-errors-when-installing-packages-globally) using a node version manager to workaround this (which is odd on its own).

**Comment by lukasholzer** [comment]
@erezrokah the odd thing is that I cannot reproduce it at all (trying my best currently with all types of node install on vms and on my mac)

**Comment by erezrokah** [comment]
Could we remove `eslint-plugin-local-rules` for now to fix this, and then publish it as a separate package?

**Review by erezrokah — APPROVED** [review]

**Pull request merged**
