### PR TITLE
Make it easier to use serve-functions programmatically

### PR DESCRIPTION
**Pull request by pimterry**
**- Summary**

See #566.

This change takes away a few of the immediate pain points for programmatic usage, e.g. building automated tests using netlify CLI to serve your functions.

More specifically, this change:
- Means that the serveFunctions promise doesn't resolve until the server has fully started up.
- Returns the newly started server, so it can be cleanly shutdown later on.
- Adds a 'quiet' option to serveFunctions to disable express-logging

There are other more dramatic ways to achieve the same goals (like a first-class `require('netlify-cli').startServer()` kind of API), but this is a very small easy step that is pretty much just as good imo.

**- Test plan**

I don't have a clear test plan for this, but I've got working automated tests locally using this to integration test my netlify functions for https://github.com/httptoolkit/accounts, where it's working very nicely.

**- Description for the changelog**

* Make it easier to use `serve-functions` programmatically

**- A picture of a cute animal (not mandatory but encouraged)**

Cute hedgehog

### CODE REVIEW

**Comment by sw-yx** [comment]
nice! up to @raeesiqbal to consider

**Comment by pimterry** [comment]
One more tweak that I missed: there's now a `watch` option you can pass to serveFunctions, defaulting to true. This lets you disable chokidar watching the test files, because otherwise the test suite won't exit when it's fully completed.

**Comment by pimterry** [comment]
Any thoughts on this @raeesbhatti? I've got all my tests working nicely now, but only locally, because I can't run them in CI until this is published.

**Comment by pimterry** [comment]
Ok I've just rebased this, and for now I've forked netlify-cli entirely and republished it to npm as [@httptoolkit/netlify-cli](https://www.npmjs.com/package/@httptoolkit/netlify-cli).

That unblocks my current work, but it'd be great to get this merged in upstream too!

**Comment by sw-yx** [comment]
agreed.

**Comment by erezrokah** [comment]
Closing as stale.
We could re-visit if needed, but one could also use the current approach the CLI uses for its own tests.
See https://github.com/netlify/cli/blob/6410f72e5e29f7b2bd8d58e8fef002d60557abd3/tests/dev.test.js#L47

**Pull request closed without merging**
