### PR TITLE
feat!: remove netlify graph commands

### PR DESCRIPTION
**Pull request by dwwoelfel**
#### Summary

Removes netlify graph commands. 

https://github.com/netlify/pod-api-ecosystem/issues/174

---

For us to review and ship your PR efficiently, please perform the following steps:

**A picture of a cute animal (not mandatory, but encouraged)**

### CODE REVIEW

**Review by eduardoboucas — APPROVED** [review]
LGTM. I think you should use `feat!` as the commit prefix though. Not only `chore` will not trigger a release, but we should make it clear that we're removing a command and that is a breaking change.

**Comment by lukasholzer** [comment]
I would love to make a pre-release and test this out properly to see if we did not break anything before merging it to the main branch

**Comment by dwwoelfel** [comment]
@lukasholzer created [15.0.0-rc.0](https://www.npmjs.com/package/netlify-cli/v/15.0.0-rc.0) and it seems to work ok for me. Is there anything in particular you wanted me to test?

**Review by lukasholzer — APPROVED** [review]
Tested plugins, dev, and build all are working fine!

**Pull request merged**
