### PR TITLE
Add new test for telemetry module, validating of eventName

### PR DESCRIPTION
**Pull request by polemius**
**- Summary**

I've add new test for telemetry module for `validation.js`.

**- Test plan**

Please, run the test.

**- Description for the changelog**

Increase test coverage by adding new test for `utils/telemetry/validation.js`.

### CODE REVIEW

**Comment by raeesbhatti** [comment]
There are currently two different logics beings used for telemetry `utils/telemetry/validation.js` and `@netlify/cli-utils/src/utils/telemetry`. They're mostly identical, so, let me see if I can pull `@netlify/cli-utils/src/utils/telemetry` into this repo before merging this.

**Comment by raeesbhatti** [comment]
Thanks for the PR btw 🌼

**Comment by polemius** [comment]
If it mostly identical, I believe I can modify this my PR and push it to `@netlify/cli-utils` or it is already tested?

**Comment by raeesbhatti** [comment]
Let me see if we want to consolidate them and where the logic is going to live.

**Pull request merged**
