### PR TITLE
chore: rename `env:migrate` to `env:clone`

### PR DESCRIPTION
**Pull request by jasonbarry**
#### Summary

Fixes https://github.com/netlify/pillar-workflow/issues/719

This PR renames the `env:migrate` command with `env:clone`. Since environment variables get copied (rather than moved) from Site A to Site B, we've [decided](https://netlify.slack.com/archives/C02TE7L1QUA/p1656548707228319?thread_ts=1656546352.164729&cid=C02TE7L1QUA) to rename the command. `migrate` has been added as an alias of `clone`, so this is a non-breaking change. 

Some prior history on the command naming: https://github.com/netlify/cli/pull/3876#pullrequestreview-841036262

---

For us to review and ship your PR efficiently, please perform the following steps:

- [x] Open a [bug/issue](https://github.com/netlify/cli/issues/new/choose) before writing your code 🧑‍💻. This ensures we can discuss the changes and get feedback from everyone that should be involved. If you\`re fixing a typo or something that\`s on fire 🔥 (e.g. incident related), you can skip this step.
- [x] Read the [contribution guidelines](../CONTRIBUTING.md) 📖. This ensures your code follows our style guide and
      passes our tests.
- [x] Update or add tests (if any source code was changed or added) 🧪
- [x] Update or add documentation (if features were changed or added) 📝
- [ ] Make sure the status checks below are successful ✅

**A picture of a cute animal (not mandatory, but encouraged)**

Screenshot 2022-07-12 at 17 36 41

### CODE REVIEW

**Comment by eduardoboucas** [comment]
You might want to rename this to `feat:` when squashing though, since `chore:` commits don't trigger a release.

**Comment by jasonbarry** [comment]
No rush on this one @eduardoboucas! I'm cool with it being lumped into the next release.

**Comment by jasonbarry** [comment]
Shoot, just missed it -- can it be changed retroactively?

**Comment by eduardoboucas** [comment]
I'm not sure! 🤔 But it's not a big deal, don't worry about it.

**Pull request merged**
