### PR TITLE
Fix rewrite force behavior for static files

### PR DESCRIPTION
**Pull request by RaeesBhatti**
**- Summary**
Fixes: https://github.com/netlify/cli/issues/705

**- Test plan**

Add `index.html` and `404.html` as static files. Set `_redirects` to:

```
/*  /404.html  200
```

Navigate to `/index.html`. `404.html` will **not be displayed**.

**- Description for the changelog**
Make sure to trim `/` from pathname when resolving path to check for static files.

**- A picture of a cute animal (not mandatory but encouraged)**
🐵

### CODE REVIEW

**Comment by sanderfish** [comment]
I think I was running into the issue fixed in this PR, but I'm unable to upgrade netlify-cli to 2.41.0. Would it be possible to publish the latest version on NPM?

**Comment by RaeesBhatti** [comment]
@sanderfish `2.41.0` has been published now. Please try again

**Comment by sanderfish** [comment]
@RaeesBhatti that was quick, thank you! I'm getting some odd behaviour with this latest version. Specifically:

- running `netlify dev` starts the server then starts displaying .......... and adds a dot for every second it's running
- running `netlify dev --dir=public` starts the server at port 3999 and then says `Waiting for localhost:34567....................................................`. It keeps adding a dot for every second it's running.
- _redirects rule of `/* https://othersite.com/:splat 200!` renders "Forbidden"

Should I move this to an issue?

**Comment by RaeesBhatti** [comment]
@sanderfish that seems like a bug 😅. Please open an issue for it and add steps to reproduce while I try to hunt that down

**Pull request merged**
