### PR TITLE
refactor: remove unused function detectAwsSdkError

### PR DESCRIPTION
**Pull request by tinfoil-knight**
**- Summary**

Found an unused function while working on #3382 in `src/lib/functions/utils.js`. 

@ehmicky wanted to confirm with the author to avoid any unintentional changes so a separate PR has been created.

**- Test plan**

`npx ava --verbose --serial`

### CODE REVIEW

**Comment by ehmicky** [comment]
Thanks @tinfoil-knight!

It appears that this code was added in https://github.com/netlify/cli/pull/2799/files#diff-a533fc859ae76f3974782aff19d74d697ff83bf2cec5c6ce8f04f742d5946f93R49, but that the following PR: https://github.com/netlify/cli/pull/2826/files#diff-a533fc859ae76f3974782aff19d74d697ff83bf2cec5c6ce8f04f742d5946f93L49 made it unused.

@eduardoboucas Was this intentional? Can this code be removed?

**Comment by eduardoboucas** [comment]
> Thanks @tinfoil-knight!
> 
> It appears that this code was added in https://github.com/netlify/cli/pull/2799/files#diff-a533fc859ae76f3974782aff19d74d697ff83bf2cec5c6ce8f04f742d5946f93R49, but that the following PR: https://github.com/netlify/cli/pull/2826/files#diff-a533fc859ae76f3974782aff19d74d697ff83bf2cec5c6ce8f04f742d5946f93L49 made it unused.
> 
> @eduardoboucas Was this intentional? Can this code be removed?

Wow, nice catch. Thanks for flagging!

The removal was _not_ intentional. The code should be there, as it provides a useful error message for people who might assume that the `aws-sdk` module is included by default.

**Comment by tinfoil-knight** [comment]
@ehmicky Should I close this PR and create another for adding back the `detectAwsSdkError` in `src/lib/functions/synchronous.js` ?

**Comment by ehmicky** [comment]
Yes, this sounds good, thanks a lot @tinfoil-knight! You should add @eduardoboucas as a reviewer for that one, because he's got more insights into this.

**Comment by eduardoboucas** [comment]
Thanks @tinfoil-knight! 🙌🏻

**Pull request closed without merging**
