### PR TITLE
fix: add back missing aws-sdk dep warning

### PR DESCRIPTION
**Pull request by tinfoil-knight**
**- Summary**

It was found out in #3383 that a function to detect if the `aws-sdk` is installed was unintentionally omitted.
Just adding it back in this PR.

**- Test plan**

`npx ava --verbose --serial`

### CODE REVIEW

**Comment by tinfoil-knight** [comment]
A few errors came up while running tests. Working on them.

**Comment by tinfoil-knight** [comment]
`lm:info` is timing out at 300s on windows. All other tests are passing.

**Comment by ehmicky** [comment]
This looks good to me. @eduardoboucas What do you think?

**Review by eduardoboucas — APPROVED** [review]
LGTM!

**Pull request merged**
