### PR TITLE
feat: remove warning for default functions directory

### PR DESCRIPTION
**Pull request by eduardoboucas**
**- Summary**

As part of https://github.com/netlify/build/issues/2016, we're updating the default functions directory to be `netlify/functions`, and therefore the current warning message is no longer relevant.

**- Test plan**

N/A

**- Description for the changelog**

feat: remove warning for default functions directory

**- A picture of a cute animal (not mandatory but encouraged)**

cute-baby-animals-31

### CODE REVIEW

**Comment by eduardoboucas** [comment]
@erezrokah At first I thought it'd be a good idea to keep the deprecations file (even though we don't have any deprecation messages currently), to serve as a skeleton for future cases, but I'm not so sure now. What do you think?

**Comment by erezrokah** [comment]
> @erezrokah At first I thought it'd be a good idea to keep the deprecations file (even though we don't have any deprecation messages currently), to serve as a skeleton for future cases, but I'm not so sure now. What do you think?

I'd say remove it - we can always add it back based on history.

**Comment by eduardoboucas** [comment]
> I'd say remove it - we can always add it back based on history.

https://github.com/netlify/cli/pull/1804/commits/86a3b9d44174fffd23f24d7c660a7db0cd0a49a5 ✅

**Review by erezrokah — APPROVED** [review]
🚀

**Pull request merged**
