### PR TITLE
Deploy: Add a timeout flag

### PR DESCRIPTION
**Pull request by raeesbhatti**
**- Summary**
Add a new flag (`-p`) to `netlify deploy` to allow users to configure timeout for deployments.

**- Test plan**

* Run `netlify deploy -p 5`
* Expect to error out if deployment takes more than five seconds

**- Description for the changelog**

* Add new flag (`--timeout`) to `deploy` command

**- A picture of a cute animal (not mandatory but encouraged)**
🐶

### CODE REVIEW

**Comment by DavidWells** [comment]
noiceeeeee!

**Comment by sw-yx** [comment]
offer to persist this preference?

**Comment by raeesbhatti** [comment]
@sw-yx Since this flag will be heavily used in automated environments, it think we should keep the whole flow non-interactive.

**Comment by sw-yx** [comment]
k

**Pull request merged**
