### PR TITLE
Display more informative error information in TimeoutError response body

### LINKED ISSUE #1459: [Functions] Response body after Timeout is mangled and non-informative
**Describe the bug**

The response of a Netlify Function incurring in timeout is `�[91mâ—ˆ�[39m Function invocation failed: [object Object]` instead of a clear explanation of the timeout issue.

**To Reproduce**

1. Create a function taking >10s to perform:
	```js
	async function handler(event, context, callback) {
	  await new Promise((r) => setTimeout(r, 20_000))
	  return callback(null, {})
	}
	```
2. Run `netlify dev`
3. Call the associated endpoint
4. Wait 10s (the default timeout)
4. Response will be non-informative and malformatted:
	```
	HTTP/1.1 500 Internal Server Error

	[91mâ—ˆ[39m Function invocation failed: [object Object]
	```

**Configuration**

- `netlify.toml`:
	```
	[build]
	  functions = "./functions"
	
	[dev]
	  framework = "create-react-app"
	```
- `npx envinfo`:
	```
	  System:
	    OS: macOS 10.15.7
	    CPU: (8) x64 Intel(R) Core(TM) i7-8559U CPU @ 2.70GHz
	    Memory: 279.05 MB / 16.00 GB
	    Shell: 5.7.1 - /bin/zsh
	  Binaries:
	    Node: 12.16.1 - ~/.nvm/versions/node/v12.16.1/bin/node
	    Yarn: 1.16.0 - ~/.yarn/bin/yarn
	    npm: 6.13.4 - ~/.nvm/versions/node/v12.16.1/bin/npm
	```

**Expected behavior**

A more informative output.
Maybe in JSON format, or customizable by the user?

**CLI Output**

```
◈ Error during invocation: {
  errorMessage: 'Task timed out after 10.00 seconds',
  errorType: 'TimeoutError',
  stackTrace: [
    'new TimeoutError (.../node_modules/netlify-cli/node_modules/lambda-local/build/lib/utils.js:110:28)',
    'Context.<anonymous> (.../node_modules/netlify-cli/node_modules/lambda-local/build/lib/context.js:110:19)',
    'listOnTimeout (internal/timers.js:549:17)',
    'processTimers (internal/timers.js:492:7)'
  ],
  level: 'error',
  [Symbol(level)]: 'error',
  [Symbol(message)]: '{"errorMessage":"Task timed out after 10.00 seconds","errorType":"TimeoutError","stackTrace":["new TimeoutError (.../node_modules/netlify-cli/node_modules/lambda-local/build/lib/utils.js:110:28)","Context.<anonymous> (.../node_modules/netlify-cli/node_modules/lambda-local/build/lib/context.js:110:19)","listOnTimeout (internal/timers.js:549:17)","processTimers (internal/timers.js:492:7)"],"level":"error"}'
}
```

**Additional context**

This is what I've found:
- the message `Function invocation failed` is created here:
	https://github.com/netlify/cli/blob/f1b2502a481068d137f14794416b01491c1f2b0e/src/utils/serve-functions.js#L20-L25
- it's prepended with a terminal-colored `◈` char for console output, but being not used in console this messes up the output with non utf-8 chars
- the `[object Object]`	is the result of an `error.toString()` on something which apparently inherits from Object
- the `TimeoutError` is generated by `lambda-local`, but gets later translated into a plain Object here:
	https://github.com/ashiina/lambda-local/blob/develop/src/lib/context.ts#L181-L185

I am now going to write a quick PR to make the actual error appear in the HTTP body.

### PR DESCRIPTION
**Pull request by caesarsol**
**- Summary**

Closes #1459, problem described with detail in relative issue.
There are more elegant ways to solve this, but I would delay them to later times. This is kind of a quick but solid workaround.

I also removed the colored `◈` from the response body (ANSI chars), and changed the console log message to include the same exact failure message of the response: "Function invocation failed" (was slightly different, creating confusion).

**- Test plan**

Tested as described in #1459 with a TimeoutError, and by manually causing a `new Error` in the code.
Knowing what else can cause an error would help in triggering other possible error types.

**- Description for the changelog**

- Error 500 "Function invocation failed" message is more informative in both response body and console log (for example a TimeoutError)

**- A picture of a cute animal (not mandatory but encouraged)**

cute cat

Thanks! ;)

### CODE REVIEW

**Review by erezrokah — CHANGES_REQUESTED** [review]
Thank you for this @caesarsol, I believe you'll need to run `npm run format` to fix the linting errors on CI

**Comment by caesarsol** [comment]
Sorry about that! I'll do whenever I find the time.

**Comment by caesarsol** [comment]
Rewrote commit!

**Comment by caesarsol** [comment]
Solved conflict and linting problem

**Review by erezrokah — APPROVED** [review]
@caesarsol sorry for the late follow up on this.
I made some additional fixes:
1. When `err` is not a lambda error, it is a string, not an error instance - changed the code accordingly.
2. When the error comes from lambda it was already logged by `winston` so no need to `console.log` it again (it is logged as JSON as the moment but that's another issue).
3. Extracted the custom validation Netlify CLI does on lambda response to a separate function.

Please let me know what you think.

**Pull request merged**
