### PR TITLE
feat(command-dev): add support for functionsPort flag fixes #3980

### LINKED ISSUE #3980: Allow specifying functions server port for `netlify dev` via flag
**Is your feature request related to a problem? Please describe.**
Every time I start `netlify dev`, functions run on different port. It makes it hard to create a collection of test requests in tools like Postman, because every time I need to change port number.

**Describe the solution you'd like**
I propose new parameter `--functionsPort` that would make possible to specify which port functions server runs on.

**Describe alternatives you've considered**
None

**Can you submit a pull request?**
No

### PR DESCRIPTION
**Pull request by tinfoil-knight**
#### Summary

`netlify dev` already supports specifying the `functionsPort` setting used to set the port for functions server in `netlify.toml`. 

Now, the `functionsPort` can now be specified through a command line flag too like:

`netlify dev --functionsPort <port>`

Fixes: #3980

---

For us to review and ship your PR efficiently, please perform the following steps:

- [x] Open a [bug/issue](https://github.com/netlify/cli/issues/new/choose) before writing your code 🧑‍💻. This ensures we can discuss the changes and get feedback from everyone that should be involved. If you\`re fixing a typo or something that\`s on fire 🔥 (e.g. incident related), you can skip this step.
- [x] Read the [contribution guidelines](../CONTRIBUTING.md) 📖. This ensures your code follows our style guide and
      passes our tests.
- [ ] Update or add tests (if any source code was changed or added) 🧪
- [x] Update or add documentation (if features were changed or added) 📝
- [x] Make sure the status checks below are successful ✅

### CODE REVIEW

**Comment by lukasholzer** [comment]
@tinfoil-knight thanks for taking the time to contribute to the CLI. Can you please reference the issue here that you are solving?

Just to get more background on the fix and to understand the problem

**Comment by tinfoil-knight** [comment]
@lukasholzer The issue number is available in the title. I've also added it now to the description above. 
Issue Link: https://github.com/netlify/cli/issues/3980

**Comment by tinfoil-knight** [comment]
@lukasholzer While this issue adds a command line flag and documents it, I couldn't find the source repo for adding it to this page: [docs.netlify.com/configure-builds/file-based-configuration/#netlify-dev](https://docs.netlify.com/configure-builds/file-based-configuration/#netlify-dev) which should ideally have the list of all supported options in `netlify.toml`

**Comment by lukasholzer** [comment]
> @lukasholzer The issue number is available in the title. I've also added it now to the description above. Issue Link: #3980

Thx, sorry have not seen this inside the title 🤦🏻‍♂️ – please always fill out the template correctly as GitHub auto detects words like `Fixes #....` and automatically links the PR to the issue. This means if it is linked it gets automatically closed on merging the PR :)

**Comment by lukasholzer** [comment]
> @lukasholzer While this issue adds a command line flag and documents it, I couldn't find the source repo for adding it to this page: [docs.netlify.com/configure-builds/file-based-configuration/#netlify-dev](https://docs.netlify.com/configure-builds/file-based-configuration/#netlify-dev) which should ideally have the list of all supported options in `netlify.toml`

Yea this has to be documented in our private repository: https://github.com/netlify/docs but I can do this for you :)

**Comment by tinfoil-knight** [comment]
> > @lukasholzer The issue number is available in the title. I've also added it now to the description above. Issue Link: #3980
> 
> Thx, sorry have not seen this inside the title 🤦🏻‍♂️ – please always fill out the template correctly as GitHub auto detects words like `Fixes #....` and automatically links the PR to the issue. This means if it is linked it gets automatically closed on merging the PR :)

My bad. Will remember from next time.

**Review by lukasholzer — APPROVED** [review]

**Comment by lukasholzer** [comment]
cc @KyleBlankRollins maybe you can outline the docs strategy on how we should document this. As flags are not documented on the file based configuration at all and I cannot find the `functionsPort` option either.

**Comment by erezrokah** [comment]
Thanks @tinfoil-knight for the PR and @lukasholzer for the review 🚀 

We should also update https://github.com/netlify/cli/blob/41e6729c7413a170d96e6a6020b7200a478976bb/docs/netlify-dev.md#netlifytoml-dev-block, which is part of the CLI repo.

@lukasholzer for the docs site, we can open an issue on our private repo and link this PR and the relevant docs section (https://docs.netlify.com/configure-builds/file-based-configuration/#netlify-dev).

**Comment by lukasholzer** [comment]
@erezrokah I opened up a docs PR in our repository: https://github.com/netlify/docs/pull/1700

**Pull request merged**
