### PR TITLE
chore: migrate docs to es modules

### PR DESCRIPTION
**Pull request by lukasholzer**
🎉 Thanks for submitting a pull request! 🎉

#### Summary

Part of the incremental migration to esmodules migrate the docs

---

For us to review and ship your PR efficiently, please perform the following steps:

- [x] Open a [bug/issue](https://github.com/netlify/cli/issues/new/choose) before writing your code 🧑‍💻. This ensures we can discuss the changes and get feedback from everyone that should be involved. If you\`re fixing a typo or something that\`s on fire 🔥 (e.g. incident related), you can skip this step.
- [x] Read the [contribution guidelines](../CONTRIBUTING.md) 📖. This ensures your code follows our style guide and
      passes our tests.
- [x] Update or add tests (if any source code was changed or added) 🧪
- [x] Update or add documentation (if features were changed or added) 📝
- [x] Make sure the status checks below are successful ✅

**A picture of a cute animal (not mandatory, but encouraged)**

### CODE REVIEW

**Review by erezrokah — DISMISSED** [review]

**Comment by lukasholzer** [comment]
@erezrokah the deploy of the docs is failing as it executes the `.js` file. But in the repository this is not configured anymore:

CleanShot 2022-01-28 at 14 01 19


Is there a different place where this is configured? or is netlify using the `main` branch for the command?

**Comment by erezrokah** [comment]
> @erezrokah the deploy of the docs is failing as it executes the `.js` file. But in the repository this is not configured anymore:

We `cd` into the `site` directory so this https://github.com/netlify/cli/blob/40b1cf9b45e78d07817829323320ea8a90c476e4/site/package.json#L19 should be updated too

**Comment by lukasholzer** [comment]
> > @erezrokah the deploy of the docs is failing as it executes the `.js` file. But in the repository this is not configured anymore:
> 
> We `cd` into the `site` directory so this
> 
> https://github.com/netlify/cli/blob/40b1cf9b45e78d07817829323320ea8a90c476e4/site/package.json#L19
> 
> should be updated too (see my latest commit)

oh was completely over looking this detail always was searching for the full path 🤦

**Review by erezrokah — APPROVED** [review]
🚀

**Comment by lukasholzer** [comment]
depends on #4143

**Pull request merged**
