### PR TITLE
feat: add context to deploy command

### LINKED ISSUE #3897: Cannot set build context when using `netlify deploy --build`
**Describe the bug**

You cannot set the build context when you are building via the deploy command.

Due to [this issue](https://github.com/netlify/cli/issues/3792) I must use `netlify deploy --build` rather than `netlify build` followed by `netlify deploy`.

**To Reproduce**

When you run `netlify build --context deploy-preview` in any repo you will see the output will say:

```
❯ Context
  deploy-preview
```

When you then run `netlify deploy --build --context deploy-preview` you get:

```
Error: unknown option '--context'
```

**Expected behavior**

Accept the`--context` flag in the `deploy` command and pass it through to the building step.

### PR DESCRIPTION
**Pull request by gavinhenderson**
🎉 Thanks for submitting a pull request! 🎉

#### Summary

Fixes #3897 

Adds a `--context` flag to the deploy command to be used with the `--build` flag.

We could rename the flag to `--buildContext` but I personally prefer using `--context` to keep the flag name consistent between the `deploy` and `build` flag. We also explicitly call out in the command help that it sets the build context which I think makes it clear enough its a build context flag.

---

For us to review and ship your PR efficiently, please perform the following steps:

- [x] Open a [bug/issue](https://github.com/netlify/cli/issues/new/choose) before writing your code 🧑‍💻. This ensures we can discuss the changes and get feedback from everyone that should be involved. If you\`re fixing a typo or something that\`s on fire 🔥 (e.g. incident related), you can skip this step.
- [x] Read the [contribution guidelines](../CONTRIBUTING.md) 📖. This ensures your code follows our style guide and
      passes our tests.
- [x] Update or add tests (if any source code was changed or added) 🧪
- [x] Update or add documentation (if features were changed or added) 📝
- [ ] Make sure the status checks below are successful ✅

**A picture of a cute animal (not mandatory, but encouraged)**

### CODE REVIEW

**Comment by gavinhenderson** [comment]
@erezrokah is there anything blocking this getting merged?

**Comment by erezrokah** [comment]
> @erezrokah is there anything blocking this getting merged?

Hey @gavinhenderson, sorry for the delay. The code change is good. We're going to discuss this internally a bit to figure out the best name for the argument, to make sure users know it only impacts the build aspect.

I think adding a validation that you can only use that argument if you pass `--build` can help.

**Comment by gavinhenderson** [comment]
@erezrokah Thanks for the update!

Since opening this PR I have done a little digging. I used to set the context when building (from the deploy command) using the `CONTEXT` env variable. For example: 

```
CONTEXT=deploy-preview netlify deploy --alias=my-alias --build
```

This stopped working in version [8.1.4](https://github.com/netlify/cli/releases/tag/v8.1.4). I tried to track down the change in that version that meant it didn't check the env variable anymore, but couldnt figure it out. 

I am now pinned to 8.1.3, which isn't ideal but as soon as this PR is merged i'll be able to upgrade to latest.  

Appreciate all your work!

**Review by erezrokah — APPROVED** [review]
Added a clarification so people know `--context` should only be used with `--build`.

Also see https://github.com/netlify/cli/pull/4040

**Pull request merged**
