### PR TITLE
feat: show progress while waiting for framework server to start

### LINKED ISSUE #3288: feat: show progress while waiting for framework server to start
**Is your feature request related to a problem? Please describe.**

Related to https://github.com/netlify/cli/issues/3242#issuecomment-910116127

When we start a framework server (e.g. Gatsby) we try to connect to the default port of that framework.
However, if a user configures a custom port they should tell `netlify dev` about it.

The problem is that `netlify dev` times out after 10 minutes and does't show any kind of progress while waiting for the framework server to start, so the user thinks the CLI is stuck and has not way of knowing what the problem is.

Most users won't wait 10 minutes for the CLI to timeout.

**Describe the solution you'd like**

The CLI should show some kind of progress while waiting to the framework server to start, detailing the port its trying to connect to and how to configure it.

> This is a bit tricky since CLI logs are interleaved with the framework process logs

**Describe alternatives you've considered**

Possibly detecting the configured port, but that's a bigger lift

**Additional context**

https://github.com/netlify/cli/issues/3242#issuecomment-910116127

**Can you submit a pull request?**

Yes

### PR DESCRIPTION
**Pull request by ericapisani**
#### Summary

Fixes #3288 

From the issue linked above:

> When we start a framework server (e.g. Gatsby) we try to connect to the default port of that framework.
> However, if a user configures a custom port they should tell netlify dev about it.
> 
> The problem is that netlify dev times out after 10 minutes and does't show any kind of progress while waiting for the framework server to start, so the user thinks the CLI is stuck and has no way of knowing what the problem is.
> 
> Most users won't wait 10 minutes for the CLI to timeout.
> 
> The CLI should show some kind of progress while waiting to the framework server to start, detailing the port its trying to connect to and how to configure it.

**Before video**
https://user-images.githubusercontent.com/5655473/172719545-9a84bc50-1ffd-474a-8723-d947b1ba46e3.mov

**After video**
https://user-images.githubusercontent.com/5655473/172719578-6f06de6a-a45d-4f7b-9ddf-83478b139ddb.mov

## Related documentation/notes
* Available options for us in the `wait-port` package are only 'dots' or 'silent', related code can be found [here](https://github.com/dwmkerr/wait-port/blob/2e7093c00ccc93dcf6097e6374e44abe2de4b118/lib/output-functions/index.js)
* Determined it was the `targetPort` we were waiting for based on the `netlify dev` [docs](https://docs.netlify.com/configure-builds/file-based-configuration/#netlify-dev)

---

For us to review and ship your PR efficiently, please perform the following steps:

- [x] Open a [bug/issue](https://github.com/netlify/cli/issues/new/choose) before writing your code 🧑‍💻. This ensures we can discuss the changes and get feedback from everyone that should be involved. If you\`re fixing a typo or something that\`s on fire 🔥 (e.g. incident related), you can skip this step.
- [x] Read the [contribution guidelines](../CONTRIBUTING.md) 📖. This ensures your code follows our style guide and
      passes our tests.
- [x] Update or add tests (if any source code was changed or added) 🧪
- [x] Update or add documentation (if features were changed or added) 📝
- [ ] Make sure the status checks below are successful ✅

**A picture of a cute animal (not mandatory, but encouraged)**
Sea_Otter_(Enhydra_lutris)_(25169790524)_crop

### CODE REVIEW

**Review by nickytonline — APPROVED** [review]
Tested locally and works great!

https://user-images.githubusercontent.com/833231/173141320-d5c5c5ad-9be4-441c-8600-bbc8d24251d1.mp4

!

**Comment by danez** [comment]
We have some random test failures now, that sometimes contain a `.` and I think this comes from this PR.

https://github.com/netlify/cli/runs/6925957490?check_suite_focus=true

Can you have a look, why this is happening?

**Comment by nickytonline** [comment]
@danez, @ericapisani is currently on PTO for the next little while. I know she had put something in place to make the snapshot tests consistent with the dots. How big a blocker is it at the moment? Is it occasional or pretty frequent the failures?

**Comment by danez** [comment]
Ah okay, then i will see if i can figure something out maybe. It is not super urgent, nothing that can't wait a little.

**Pull request merged**
