### PR TITLE
chore(gh-auth): minor refactoring

### PR DESCRIPTION
**Pull request by XhmikosR**
🎉 Thanks for submitting a pull request! 🎉

#### Summary

Just a minor refactoring. Let me know if you don't like the ternary change and I'll revert it.

---

For us to review and ship your PR efficiently, please perform the following steps:

- [ ] Open a [bug/issue](https://github.com/netlify/cli/issues/new/choose) before writing your code 🧑‍💻. This ensures we can discuss the changes and get feedback from everyone that should be involved. If you\`re fixing a typo or something that\`s on fire 🔥 (e.g. incident related), you can skip this step.
- [x] Read the [contribution guidelines](../CONTRIBUTING.md) 📖. This ensures your code follows our style guide and
      passes our tests.
- [x] Update or add tests (if any source code was changed or added) 🧪
- [x] Update or add documentation (if features were changed or added) 📝
- [x] Make sure the status checks below are successful ✅

**A picture of a cute animal (not mandatory, but encouraged)**

### CODE REVIEW

**Review by erezrokah — APPROVED** [review]
This is much better 👍

**Comment by XhmikosR** [comment]
@erezrokah is it me or I can't no longer login to Netlify?

**Comment by erezrokah** [comment]
> @erezrokah is it me or I can't no longer login to Netlify?

Is this still an issue? Going to play the "it works for me card".

If it's still an issue the best would be to reach out to our support using https://www.netlify.com/support/, as they'll be able to collect the relevant information to solve it.

**Comment by XhmikosR** [comment]
Hmm, I see what's going on. The Netlify site opens for me properly, I login it, but then I'm not redirected to the new app to allow it.

If one is already logged in, then it works.

**Pull request merged**
