### PR TITLE
fix: fixes an issue where the --dir flag on the deploy command was broken

### PR DESCRIPTION
**Pull request by lukasholzer**
🎉 Thanks for submitting a pull request! 🎉

#### Summary

Fixes https://github.com/netlify/cli/issues/5949

---

For us to review and ship your PR efficiently, please perform the following steps:

- [ ] Open a [bug/issue](https://github.com/netlify/cli/issues/new/choose) before writing your code 🧑‍💻. This ensures we can discuss the changes and get feedback from everyone that should be involved. If you\`re fixing a typo or something that\`s on fire 🔥 (e.g. incident related), you can skip this step.
- [ ] Read the [contribution guidelines](../CONTRIBUTING.md) 📖. This ensures your code follows our style guide and
      passes our tests.
- [ ] Update or add tests (if any source code was changed or added) 🧪
- [ ] Update or add documentation (if features were changed or added) 📝
- [ ] Make sure the status checks below are successful ✅

**A picture of a cute animal (not mandatory, but encouraged)**

### CODE REVIEW

**Review by estephinson — APPROVED** [review]

**Review by eduardoboucas — APPROVED** [review]

**Comment by JamesAwesome** [comment]
Strangely the bug regarding the `--dir` flag is only now affecting me. The `netlify deploy` command now seems to entirely ignore `--dir` and always deploys `cwd`

**Comment by South-Paw** [comment]
Also noticed this @JamesAwesome

A GitHub action CI deploy command uploaded the entire monorepo to Netlify rather than just the specified `--dir` 🤔

**Comment by lukasholzer** [comment]
@JamesAwesome, sorry for introducing this bug. It should be fixed in  16.3.4 please let us know if something is not working as expected.

**Comment by JamesAwesome** [comment]
Thank you!

**Pull request merged**
