### PR TITLE
test: disable flaky tests on windows

### PR DESCRIPTION
**Pull request by lukasholzer**
🎉 Thanks for submitting a pull request! 🎉

#### Summary

Disable flaky tests on windows:

These two where always failing and blocking 
https://github.com/netlify/cli/runs/4896037137?check_suite_focus=true

I curated a list of flaky tests and those two are failing more often
https://www.notion.so/netlify/Flaky-CLI-Test-1d125bd140da4d1dbdb05ca02113d46d (internal link)

For us to review and ship your PR efficiently, please perform the following steps:

- [x] Open a [bug/issue](https://github.com/netlify/cli/issues/new/choose) before writing your code 🧑‍💻. This ensures we can discuss the changes and get feedback from everyone that should be involved. If you\`re fixing a typo or something that\`s on fire 🔥 (e.g. incident related), you can skip this step.
- [x] Read the [contribution guidelines](../CONTRIBUTING.md) 📖. This ensures your code follows our style guide and
      passes our tests.
- [x] Update or add tests (if any source code was changed or added) 🧪
- [x] Update or add documentation (if features were changed or added) 📝
- [x] Make sure the status checks below are successful ✅

**A picture of a cute animal (not mandatory, but encouraged)**

### CODE REVIEW

**Comment by lukasholzer** [comment]
FYI @XhmikosR

**Review by erezrokah — APPROVED** [review]

**Comment by XhmikosR** [comment]
Doesn't seem to fix all failures :/ https://github.com/netlify/cli/runs/4898013668?check_suite_focus=true

There must be a way to circumvent the affected tests script BTW. In this PR only a few tests ran :)

**Comment by lukasholzer** [comment]
I forgot this one updated already a pr: https://github.com/netlify/cli/pull/4102

**Comment by lukasholzer** [comment]
@XhmikosR why should we find a way around the affected test script? this was good that only this test was running as no others where affected by the changset.

The problem is when the lockfile or the package.json is touched all tests are run as it can potentially influence all (which causes often troubles as running only few of them is not causing issues only the majority of running in paralell is causing fs issues especially on windows)

**Comment by XhmikosR** [comment]
Because in this case you couldn't test everything due to the nature of that script :)

**Pull request merged**
