### PR TITLE
chore: fix GitHub action checking for install size

### PR DESCRIPTION
**Pull request by ehmicky**
See https://github.com/netlify/cli/pull/4041#discussion_r785051424

This fixes the GitHub action which checks for the npm package's published size, to exclude `devDependencies`.

cc @XhmikosR 

---

For us to review and ship your PR efficiently, please perform the following steps:

- [x] Open a [bug/issue](https://github.com/netlify/cli/issues/new/choose) before writing your code 🧑‍💻. This ensures we can discuss the changes and get feedback from everyone that should be involved. If you\`re fixing a typo or something that\`s on fire 🔥 (e.g. incident related), you can skip this step.
- [x] Read the [contribution guidelines](../CONTRIBUTING.md) 📖. This ensures your code follows our style guide and
      passes our tests.
- [x] Update or add tests (if any source code was changed or added) 🧪
- [x] Update or add documentation (if features were changed or added) 📝
- [x] Make sure the status checks below are successful ✅

### CODE REVIEW

**Comment by XhmikosR** [comment]
LGTM!

Your call if you'll go with 2 lines or one :)

```yml
        run: |
          npm ci --no-audit
          npm prune --production
```

**Review by erezrokah — APPROVED** [review]

**Comment by ehmicky** [comment]
I initially used two lines, but my IDE somehow complained about the syntax :thinking:

**Comment by XhmikosR** [comment]
As long as indentation is correct, it should be fine since it's perfectly valid YAML :)

**Comment by ehmicky** [comment]
Yes, it should! I am not quite sure why this was failing :thinking:

**Pull request merged**
