### PR TITLE
feat: add flag to skip env var fetching

### PR DESCRIPTION
**Pull request by davbree**
🎉 Thanks for submitting a pull request! 🎉

#### Summary

Introduce internal option `--offline-env` to disable using any env vars fetched from the API.
This offers better support for the case of receiving all env vars externally (via devbot).

ref CRE-1078

---

For us to review and ship your PR efficiently, please perform the following steps:

- [ ] Open a [bug/issue](https://github.com/netlify/cli/issues/new/choose) before writing your code 🧑‍💻. This ensures we can discuss the changes and get feedback from everyone that should be involved. If you\`re fixing a typo or something that\`s on fire 🔥 (e.g. incident related), you can skip this step.
- [ ] Read the [contribution guidelines](../CONTRIBUTING.md) 📖. This ensures your code follows our style guide and
      passes our tests.
- [ ] Update or add tests (if any source code was changed or added) 🧪
- [ ] Update or add documentation (if features were changed or added) 📝
- [ ] Make sure the status checks below are successful ✅

**A picture of a cute animal (not mandatory, but encouraged)**

### CODE REVIEW

**Review by smnh — APPROVED** [review]

**Comment by lukasholzer** [comment]
why cannot we use the existing `--offline` flag for it?

**Comment by davbree** [comment]
We still want to fetch the site config (for the dev command and target port). I could provide that from bitballoon as well in the future and then we can use `--offline` (and remove `--offline-env`)

**Comment by lukasholzer** [comment]
> We still want to fetch the site config (for the dev command and target port). I could provide that from bitballoon as well in the future (CRE-1431) and then we can use `--offline` (and remove `--offline-env`)

As this is public API on the CLI we should provide that probably first to be able to leverage the --offline flag.

**Comment by davbree** [comment]
I'm using `hideHelp(true)` to keep things internal (like we do for other parameters). Makes it easier to do this not all together..

**Pull request merged**
