### PR TITLE
fix(deploy): handle 404

### PR DESCRIPTION
**Pull request by gergelyke**
Hi folks 👋 

just had to spend quite some time tracking down a bug, which eventually happened because we set a wrong site id. If this error message had been in place, it could have save me quite a few hours.

### CODE REVIEW

**Comment by RaeesBhatti** [comment]
Thanks for creating this PR @gergelyke

**Comment by RaeesBhatti** [comment]
Just wondering did you create an issue ticket for this error?

**Comment by gergelyke** [comment]
No, I didn't - just went ahead and fixed it. I hope that's fine :)

**Comment by RaeesBhatti** [comment]
Fine in this case because the issue and fix seem obvious. Thanks 👍

**Pull request merged**
