### PR TITLE
Upgrade Netlify Build

### PR DESCRIPTION
**Pull request by ehmicky**
This upgrades `@netlify/build` and `@netlify/config` to the latest version.

One major change is that the `build.lifecycle` property is now deprecated.

### CODE REVIEW

**Comment by RaeesBhatti** [comment]
It seems like the same test is failing on Windows again and again. Can you take a look!

**Comment by ehmicky** [comment]
I have opened #854 for this. The tests are failing on Windows, but this does not appear to be related to this PR.

**Comment by ehmicky** [comment]
Looking into it now.

**Comment by ehmicky** [comment]
Fixed!

**Pull request merged**
