### PR TITLE
Dev: Fix Netlify Functions logging

### PR DESCRIPTION
**Pull request by RaeesBhatti**
**- Summary**
Fixes `console.log`s not working in latest version when running Netlify Functions with `netlify dev`.
Fixes: https://github.com/netlify/cli/issues/716 

**- Test plan**

* Add `console.log` to your Netlify Function and run it through `netlify dev`

**- Description for the changelog**

Use `winston` to provide custom logger for `lambda-local`

**- A picture of a cute animal (not mandatory but encouraged)**
🐥

### CODE REVIEW

**Comment by RaeesBhatti** [comment]
1. Yes, we switched from using our custom logic to invoke Netlify Function on `netlify dev` to using `lambda-local`, so that, we can support `.env` files and because `lambda-local` is more featureful. But the default logger in `lambda-local` logs input and output each Netlify Function event, which clutters the terminal. The only way to disable that was to set `verboseLevel` parameter to `0`. But setting `verboseLevel` to a number less than `3` makes `console.log` statements from Netlify Functions not show up in console because of how the default logger logic is implemented.
2. The only way to fix that without changing `lambda-local` codebase is to provide our own logger. Using `getLogger` is not useful in this context because that logger already has some custom logic that is causing the problem. Which is why we provide our own.

**Comment by erquhart** [comment]
Thanks, looks good to me! I’m cool with merging without tests, but that PR should come next - in this case just a test to ensure logs from a function work.

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by unclejustin** [comment]
@RaeesBhatti hello! Thanks for your effort on this, but it doesn't actually fix the problem for me. I'm on 2.36 which includes this change, but console.log still does nothing.

**Comment by RaeesBhatti** [comment]
@unclejustin Can you please post a sample function to reproduce this issue!

**Comment by unclejustin** [comment]
Certainly. Also note that I can put the `console.log`s anywhere and none of them ever work.

```js
const { retry, respondSuccess, respondError } = require('./utils')
const stripe = require('stripe')(process.env.STRIPE_SK)

const baseUrl = process.env.BASE_URL

exports.handler = (event, context, callback) => {
  console.log('Please work bby')
  
  switch (event.httpMethod) {
    // Code...
  }
}
```

**Comment by RaeesBhatti** [comment]
The tried the following code and it's working as expected in the latest version:
```
const baseUrl = process.env.BASE_URL

exports.handler = (event, context, callback) => {
  console.log('Please work bby')
  
  switch (event.httpMethod) {
    // Code...
  }
}
```
Can you please make sure that you do a `netlify version` in the same directory to make sure you're running the latest version. Also, maybe try global uninstall and then install again. It could also be that if you're running with `yarn` or `npx` they're using different locally installed version than the latest one.
Screen Shot 2020-02-27 at 9 22 52 PM

**Comment by unclejustin** [comment]
It was yarn! @RaeesBhatti 🙇 

Ran `netlify version` as you said and confirmed 2.35 ran which and found that I had installed initially with npm global. But "upgraded" with yarn 🤦‍♂ 

I'm all good, thanks for straightening me out 💪

**Comment by RaeesBhatti** [comment]
No problem. Glad we could figure this out! 🎉

**Pull request merged**
