### PR TITLE
Dev: Add support for JWT redirects

### PR DESCRIPTION
**Pull request by raeesbhatti**
**- Summary**
Fixes: https://github.com/netlify/cli/issues/529

**- Test plan**
Create a static files project
Have some content in file `/admin/something.html`
Have a valid file at `/login.html`
Have a file with following contents at `/_redirects`:
```
/admin/*			200!	Role=admin
/admin/*	/login	401!
```
`netlify dev`
Make an http request for `http://localhost:8888/admin/something` without any Cookie headers and expect it to fail with a 401 and contents of `/login.html` 
Make another http request for `http://localhost:8888/admin/something` with a Cookie header that has `nf_jwt=YOUR_JWT_HERE`. Expect this request to be successful. Your JWT contents similar to following:
```
{
    "app_metadata": {
      "authorization": {
        "roles": ["admin"]
      }
    },
    "exp": 2149017956
  }
```
We currently don't verify the secret for JWT. The object path for roles property (`app_metadata.authorization.roles` in the example above) can be configured by having a `jwtRolePath` value in your `netlify.toml -> [dev]`. Like so:
```
[dev]
  jwtRolePath = "app_metadata.authorization.roles"
```

Stop `netlify dev`.
Remove the second line from `/_redirects`.
Rerun `netilfy dev`
Make an http request for `http://localhost:8888/admin/something` without any Cookie headers and expect it to fail with a 404 page. 

**- Description for the changelog**
Decode `nf_jwt` Cookie and use it to match roles defined in `redirects` directives.

**- A picture of a cute animal (not mandatory but encouraged)**
🦁

### CODE REVIEW

**Comment by raeesbhatti** [comment]
@calavera is `jwtRolePath` configurable in production? If not, then I can remove that option here.

**Comment by DavidWells** [comment]
> @calavera is jwtRolePath configurable in production? If not, then I can remove that option here.

I think `jwtRolePath` is hardcoded to `app_metadata.authorization.roles`. Is this correct? @calavera or @futuregerald ?

**Comment by futuregerald** [comment]
Right now we modify it for people when they request it. It should be available via the UI and at some point it will be. I wouldn't remove it. Anyone using OIDC compliant JWT's that use domain namespacing will need to set a custom path, this particularly affects people using Auth0.

**Comment by raeesbhatti** [comment]
Can we get a thumbs up on this please! @DavidWells @calavera

**Comment by raeesbhatti** [comment]
Going to merge this, let me know if you have any objections and we can revert.

**Pull request merged**
