### PR TITLE
feat: print function URL on first load (closes #3618)

### LINKED ISSUE #3618: As a new user I don't know how to invoke my functions when served with `ntl dev`
**Is your feature request related to a problem? Please describe.**

As a new user I don't know how I can invoke my functions when running with the `ntl dev` command

**Describe the solution you'd like**

I would expect something like this on startup by running: `ntl dev`

```diff
◈ Netlify Dev ◈
◈ Ignored general context env var: LANG (defined in process)
◈ No app server detected. Using simple static server
◈ Running static server from "build-reproductions/dist"
- ◈ Loaded function hello.
+ ◈ Loaded function hello available under: http://localhost:8888/.netlify/functions/hello 
◈ Functions server is listening on 58458

◈ Static server listening to 3999

   ┌─────────────────────────────────────────────────┐
   │                                                 │
   │   ◈ Server now ready on http://localhost:8888   │
   │                                                 │
   └─────────────────────────────────────────────────┘

```

**Additional context**

Furthermore it is hard to find this information somewhere, needed some while to stumble over: https://answers.netlify.com/t/how-do-you-access-functions/746

**Can you submit a pull request?**

Yes.

### PR DESCRIPTION
**Pull request by netlify-team-account-1**
#### Summary

Fixes #3618

---

For us to review and ship your PR efficiently, please perform the following steps:

- [ ] Open a [bug/issue](https://github.com/netlify/cli/issues/new/choose) before writing your code 🧑‍💻. This ensures we can discuss the changes and get feedback from everyone that should be involved. If you\`re fixing a typo or something that\`s on fire 🔥 (e.g. incident related), you can skip this step.
- [ ] Read the [contribution guidelines](../CONTRIBUTING.md) 📖. This ensures your code follows our style guide and
      passes our tests.
- [ ] Update or add tests (if any source code was changed or added) 🧪
- [ ] Update or add documentation (if features were changed or added) 📝
- [ ] Make sure the status checks below are successful ✅

**A picture of a cute animal (not mandatory, but encouraged)**

### CODE REVIEW

**Review by eduardoboucas — COMMENTED** [review]
LGTM!

My only concern is that this adds a lot of noise to the output, especially when there are dozens of functions. Rather than adding the full URL to the log line, could we experiment with using something like https://www.npmjs.com/package/terminal-link?

@netlify-team-account-1 would you mind adding a screenshot of what the output looks like with some functions, and then we ask @joeyaiello for his thoughts?

**Comment by netlify-team-account-1** [comment]
Sure thing! @joeyaiello what are your thoughts on this?
Screenshot 2021-11-18 at 07 56 49

**Comment by netlify-team-account-1** [comment]
@joeyaiello @eduardoboucas WDYT about moving forward with this and then potentially incrementing on smth like terminal-link?

**Review by minivan — APPROVED** [review]

**Comment by netlify-team-account-1** [comment]
Added `terminal-link`, this is how it looks on iTerm2:

Screenshot 2021-12-06 at 18 12 34

Unfortunately, it works neither in standard MacOS terminal, nor in the VSCode terminal, nor in Hyper (even thought that's on the list of supported terminals!). When it doesn't work, the [fallback](https://github.com/netlify/cli/pull/3646/files#diff-3da7ce6e23397682fdafed3a9ac46e11c861e5a68ca304e8a6517e0ba75dffd1R149) looks exactly as the original screenshot,, so it's still kind of cluttered.

An alternative would be to keep the current behaviour of not printing the URL, and only `terminal-link` for supported terminals where it doesn't add any visual clutter.

**Comment by netlify-team-account-1** [comment]
yes! implemented in e722ad1

**Review by eduardoboucas — DISMISSED** [review]
LGTM!

**Review by eduardoboucas — APPROVED** [review]
🚀

**Pull request merged**
