### PR TITLE
Fix deprecation on errors

### PR DESCRIPTION
**Pull request by Berkmann18**
**- Summary**

This PR fixes deprecation warnings on `error.code` (_except what seemed to be non-native error objects with the same `code` field_).

**- Test plan**

None.

**- Description for the changelog**

Fix deprecation warnings on errors.

**- A picture of a cute animal (not mandatory but encouraged)**
image

### CODE REVIEW

**Comment by bcomnes** [comment]
Thanks @Berkmann18 !  Will review asap.

**Comment by bcomnes** [comment]
@Berkmann18 do you have a link to the origination of this change? Does it work with older versions of node too?

**Comment by bcomnes** [comment]
Oh wait, octokit.  Dang again!

**Comment by bcomnes** [comment]
Wait, node and octokit.  Sorry @Berkmann18 I'm not up on these changes, can you point me in the right direction of where you got the idea to fix these? (e.g. changelog or depreciation notices you are seeing).

**Comment by Berkmann18** [comment]
@bcomnes While I was working on a Gridsome project (I believe) and installing this package, NPM showed some warnings (which I've seen before with other packages) so I decided to try to fix them.

**Pull request merged**
