### PR TITLE
chore: add eslint-plugin-sort-destructure-keys

### PR DESCRIPTION
**Pull request by netlify-team-account-1**
**- Summary**

Idea from here: https://github.com/netlify/cli/pull/3445#discussion_r727003403

This PR introduces the `eslint-plugin-sort-destructure-keys` plugin, which forces all destructurings (including function parameter destructuring) to be sorted alphabetically.

**- Test plan**

**- A picture of a cute animal (not mandatory but encouraged)**

### CODE REVIEW

**Comment by eduardoboucas** [comment]
I feel that I should add some context here, since I wrote the initial comment.

Sorting object keys alphabetically is not a convention we've adopted. Personally, I think it makes code easier to read, especially when you have a long list of properties (which is often the case in codebases like Netlify Build and zip-it-and-ship-it). We've had [informal discussions](https://netlify.slack.com/archives/CN8S7NB29/p1628844711123500) on the subject and the majority of people seem to feel the same way.

When I write new code, I adopt that convention, and I tend to ask people to keep that order when they're adding a new property to an object that's already sorted. That was the example [here](https://github.com/netlify/cli/pull/3445/files#diff-41e7ff2f2dc80310c60a5be107c9b017bd1d3bbf9b986ed524de02d71d76a4f1R23).

If we're introducing this as a linting rule, it feels like we should do it in https://github.com/netlify/eslint-config-node, but we should definitely involve everyone from the guild to make sure they're comfortable with it.

(cc @netlify/netlify-dev)

**Comment by eduardoboucas** [comment]
> I personally prefer grouping properties by their meaning or relatedness instead.

My issue with that is that "relatedness" is a subjective criteria, which means not only that it's unenforceable using automated tools, but also it's possible that the sorting will help whoever wrote the code and nobody else.

**Comment by netlify-team-account-1** [comment]
@eduardoboucas awaiting your review, then we can merge this :)

**Comment by netlify-team-account-1** [comment]
> would we add it to CLI only at first to see how it goes and then make it part of https://github.com/netlify/eslint-config-node? 

That sounds like a good action plan.

**Pull request merged**
