### PR TITLE
feat(chore): show up local env-info with --verbose flag

### LINKED ISSUE #366: Have a dedicated flag to show up local environment information
Presently, the user is required to provide his/her local environment information as per the `issue template`. IMO it would be good to have a dedicated command for the purpose :thinking: 

## Proposed API

`netlify info`

We could utilize [envinfo](https://npmjs.com/package/envinfo)

### PR DESCRIPTION
**Pull request by jamesgeorge007**
Closes #366 

Adds a new `--verbose` flag to the `status` command which shows up the local environment information in additional to the default behaviour of `netlify status`.

### CODE REVIEW

**Comment by jamesgeorge007** [comment]
cc @DavidWells

**Comment by jamesgeorge007** [comment]
cc @DavidWells

**Comment by jamesgeorge007** [comment]
cc @DavidWells @raeesbhatti

**Comment by DavidWells** [comment]
Looks good thanks @jamesgeorge007 for the PR!

**Pull request merged**
