### PR TITLE
fix(deps): replace string-similarity with fastest-levenshtein

### PR DESCRIPTION
**Pull request by kisaragi-hiu**
#### Summary

Replace string-similarity with [fastest-levenshtein](https://github.com/ka-weihe/fastest-levenshtein) as the former is deprecated, resulting in another warning during installation.

While the algorithm is different (Levenshtein distance instead of Dice's coefficient), the difference shouldn't be big enough to matter, as this is only used for suggestion after a typo.

Partially addresses #5724.

---

For us to review and ship your PR efficiently, please perform the following steps:

- [ ] Open a [bug/issue](https://github.com/netlify/cli/issues/new/choose) before writing your code 🧑‍💻. This ensures we can discuss the changes and get feedback from everyone that should be involved. If you\`re fixing a typo or something that\`s on fire 🔥 (e.g. incident related), you can skip this step.
- [x] Read the [contribution guidelines](../CONTRIBUTING.md) 📖. This ensures your code follows our style guide and
      passes our tests.
- [ ] Update or add tests (if any source code was changed or added) 🧪
- [ ] Update or add documentation (if features were changed or added) 📝
- [ ] Make sure the status checks below are successful ✅

### CODE REVIEW

**Comment by Skn0tt** [comment]
@kisaragi-hiu thanks for the PR! The changes look good to me, but i'd like to make sure that changing the algo to Levenshtein doesn't have unintended consequences.

@lukasholzer I see you originally implemented the string similarity 2 years ago. Did you pick a sorensen-dice-based algorithm on purpose? Do you think we should stick with that, and maybe use a library like https://www.npmjs.com/package/dice-coefficient instead? Or is it fine to switch to Levenshtein?

**Review by lukasholzer — COMMENTED** [review]
@Skn0tt to be honest I cannot remember why I've decided to go along with the `string-similarity` package. 

But using the fastest Levenshtein distance is probably a good decision as it measures the necessary edits so in this case it looks pretty well suited. 

@kisaragi-hiu thanks for putting the effort into this! Looks good to me :)

Do you mind maybe adding a test to it?

**Review by Skn0tt — APPROVED** [review]
looks great! thanks so much for this PR @kisaragi-hiu!

**Review by lukasholzer — APPROVED** [review]
LGTM!

**Pull request merged**
