### PR TITLE
Add command to switch active Netlify account

### PR DESCRIPTION
**Pull request by raeesbhatti**
**- Summary**

Adds a new command (`netlify switch`) to allow you to switch between different Netlify accounts in CLI.
Fixes: https://github.com/netlify/cli/issues/105

**- Test plan**

* `netlify switch`
* Select "I would like to login to a new account". You'll be logged into the new account and your current account in CLI will be updated to reflect the latest.
* `netlify switch`, you can now see both accounts and switch between them

**- Description for the changelog**

* Adds a new flag to `netlify login` (`--new`), that allows you to login to a new Netlify account even if you're already logged in
* Adds a new command `netlify switch` that allows you to switch between already logged in accounts and login to a new one

**- A picture of a cute animal (not mandatory but encouraged)**

why-do-i-want-to-crush-cute-animals-1432782372

### CODE REVIEW

**Comment by sw-yx** [comment]
i never knew we were working on this. imo its fine to run two commands `logout` and `login` again rather than support this

**Comment by raeesbhatti** [comment]
I personally think this will be useful since doing `logout` and `login` requires following the whole login flow each time. While this is simple and quick.
Looking for more opinions.

**Comment by sw-yx** [comment]
david clarified that its useful for "Work vs personal accounts. Also agencies
And support" :) up to you really i was just adding random not very helpful comments and i will stop now

**Comment by raeesbhatti** [comment]
Haha no problem. Your comments are always welcome 🙌🏽

**Comment by raeesbhatti** [comment]
Going to merge this since there's a general positive signal. Can revert if there's an objection.

**Pull request merged**
