### PR TITLE
fix: pass bootstrapUrl to runCoreSteps

### PR DESCRIPTION
**Pull request by Skn0tt**
Closes https://github.com/netlify/pod-dev-foundations/issues/574.

### CODE REVIEW

**Comment by eduardoboucas** [comment]
I see that you're also updating esbuild as part of this, but the diff of the lock file makes me think we're now having both versions?

**Review by lukasholzer — APPROVED** [review]
LGTM!

**Comment by Skn0tt** [comment]
> I see that you're also updating esbuild as part of this, but the diff of the lock file makes me think we're now having both versions?

Looks like it. Maybe we need to also update ZISI? Will take a look.

**Comment by Skn0tt** [comment]
Done in https://github.com/netlify/cli/pull/5939/commits/b52fbe97fd7dc0cc9b0b611f70b612b053a2cbab. Good catch, Eduardo!

**Review by eduardoboucas — APPROVED** [review]

**Pull request merged**
